/**
 * @license EUPL-1.2+
 * Copyright Gemeente Amsterdam
 */

type SpaceSize = '0' | 'xs' | 's' | 'm' | 'l' | 'xl'

export const componentsAbove = [
  'Heading 1',
  'Heading 2',
  'Heading 3',
  'Heading 4',
  'Blockquote',
  '\u2026 List',
  'Paragraph',
  'Paragraph (large)',
  'Button / CTA Link',
  'Image',
  'Standalone Link',
  'Table',
]

export const componentsBelow = [
  'Heading 2',
  'Heading 3',
  'Heading 4',
  'Blockquote',
  'Button / CTA Link',
  'Image',
  'Standalone Link',
  '\u2026 List',
  'Paragraph',
  'Paragraph (large)',
  'Table',
]

export const spaceBetween: Record<string, SpaceSize> = {
  '\u2026 List|\u2026 List': 'm',
  '\u2026 List|Blockquote': 'l',
  '\u2026 List|Button / CTA Link': 'm',
  '\u2026 List|Heading 2': 'xl',
  '\u2026 List|Heading 3': 'l',
  '\u2026 List|Heading 4': 'm',
  '\u2026 List|Image': 'l',
  '\u2026 List|Paragraph': 'm',
  '\u2026 List|Standalone Link': 'm',
  '\u2026 List|Table': 'l',
  'Blockquote|\u2026 List': 'l',
  'Blockquote|Button / CTA Link': 'l',
  'Blockquote|Image': 'l',
  'Blockquote|Paragraph': 'l',
  'Blockquote|Standalone Link': 'l',
  'Blockquote|Table': 'l',
  'Button / CTA Link|\u2026 List': 'm',
  'Button / CTA Link|Blockquote': 'l',
  'Button / CTA Link|Button / CTA Link': 'l',
  'Button / CTA Link|Heading 2': 'xl',
  'Button / CTA Link|Heading 3': 'l',
  'Button / CTA Link|Heading 4': 'l',
  'Button / CTA Link|Image': 'l',
  'Button / CTA Link|Paragraph': 'm',
  'Button / CTA Link|Standalone Link': 'm',
  'Button / CTA Link|Table': 'l',
  'Heading 1|Heading 2': 'xl',
  'Heading 1|Paragraph (large)': 'm',
  'Heading 2|\u2026 List': 's',
  'Heading 2|Heading 3': 'm',
  'Heading 2|Paragraph': 's',
  'Heading 2|Table': 's',
  'Heading 3|\u2026 List': 'xs',
  'Heading 3|Heading 4': 'm',
  'Heading 3|Paragraph': 'xs',
  'Heading 3|Table': 'xs',
  'Heading 4|\u2026 List': '0',
  'Heading 4|Paragraph': '0',
  'Heading 4|Table': '0',
  'Image|\u2026 List': 'l',
  'Image|Blockquote': 'l',
  'Image|Button / CTA Link': 'l',
  'Image|Heading 2': 'xl',
  'Image|Heading 3': 'l',
  'Image|Heading 4': 'l',
  'Image|Image': 'l',
  'Image|Paragraph': 'l',
  'Image|Standalone Link': 'l',
  'Image|Table': 'l',
  'Paragraph (large)|\u2026 List': 'l',
  'Paragraph (large)|Blockquote': 'xl',
  'Paragraph (large)|Heading 2': 'xl',
  'Paragraph (large)|Image': 'xl',
  'Paragraph (large)|Paragraph': 'l',
  'Paragraph (large)|Standalone Link': 'l',
  'Paragraph (large)|Table': 'l',
  'Paragraph|\u2026 List': 'm',
  'Paragraph|Blockquote': 'l',
  'Paragraph|Button / CTA Link': 'm',
  'Paragraph|Heading 2': 'xl',
  'Paragraph|Heading 3': 'l',
  'Paragraph|Heading 4': 'm',
  'Paragraph|Image': 'l',
  'Paragraph|Paragraph': 'm',
  'Paragraph|Standalone Link': 'm',
  'Paragraph|Table': 'l',
  'Standalone Link|\u2026 List': 'm',
  'Standalone Link|Blockquote': 'l',
  'Standalone Link|Button / CTA Link': 'm',
  'Standalone Link|Heading 2': 'xl',
  'Standalone Link|Heading 3': 'l',
  'Standalone Link|Heading 4': 'l',
  'Standalone Link|Image': 'l',
  'Standalone Link|Paragraph': 'm',
  'Standalone Link|Standalone Link': 'm',
  'Standalone Link|Table': 'l',
  'Table|\u2026 List': 'l',
  'Table|Blockquote': 'l',
  'Table|Button / CTA Link': 'l',
  'Table|Heading 2': 'xl',
  'Table|Heading 3': 'l',
  'Table|Heading 4': 'l',
  'Table|Image': 'l',
  'Table|Paragraph': 'l',
  'Table|Standalone Link': 'l',
  'Table|Table': 'l',
}
