/**
 * @license EUPL-1.2+
 * Copyright Gemeente Amsterdam
 */

type SpaceSize = '0' | 'xs' | 's' | 'm' | 'l' | 'xl'

export const componentsAbove = [
  'Heading 1',
  'Heading 2',
  'Heading 3',
  'Heading 4',
  '\u2026 List',
  'Paragraph',
  'Paragraph (large)',
  'Button / CTA Link',
  'Image',
  'Standalone Link',
  'Table',
]

export const componentsBelow = [
  'Heading 2',
  'Heading 3',
  'Heading 4',
  '\u2026 List',
  'Paragraph',
  'Paragraph (large)',
  'Button / CTA Link',
  'Image',
  'Link',
  'Standalone Link',
  'Table',
]

export const spaceBetween: Record<string, SpaceSize> = {
  '\u2026 List|\u2026 List': 'm',
  '\u2026 List|Button / CTA Link': 'm',
  '\u2026 List|Heading 2': 'xl',
  '\u2026 List|Heading 3': 'l',
  '\u2026 List|Heading 4': 'l',
  '\u2026 List|Image': 'l',
  '\u2026 List|Link': 'm',
  '\u2026 List|Paragraph': 'm',
  '\u2026 List|Standalone Link': 'm',
  '\u2026 List|Table': 'l',
  'Button / CTA Link|\u2026 List': 'l',
  'Button / CTA Link|Heading 2': 'xl',
  'Button / CTA Link|Heading 3': 'l',
  'Button / CTA Link|Heading 4': 'l',
  'Button / CTA Link|Image': 'l',
  'Button / CTA Link|Link': 'm',
  'Button / CTA Link|Paragraph': 'l',
  'Button / CTA Link|Table': 'l',
  'Heading 1|Heading 2': 'xl',
  'Heading 1|Paragraph (large)': 'm',
  'Heading 2|\u2026 List': 's',
  'Heading 2|Heading 3': 'm',
  'Heading 2|Paragraph': 's',
  'Heading 2|Table': 's',
  'Heading 3|\u2026 List': 'xs',
  'Heading 3|Heading 4': 'm',
  'Heading 3|Paragraph': 'xs',
  'Heading 3|Table': 'xs',
  'Heading 4|\u2026 List': '0',
  'Heading 4|Paragraph': '0',
  'Heading 4|Table': '0',
  'Image|\u2026 List': 'l',
  'Image|Button / CTA Link': 'l',
  'Image|Heading 2': 'xl',
  'Image|Heading 3': 'xl',
  'Image|Heading 4': 'xl',
  'Image|Image': 'm',
  'Image|Link': 'l',
  'Image|Paragraph': 'l',
  'Image|Table': 'l',
  'Paragraph (large)|\u2026 List': 'm',
  'Paragraph (large)|Button / CTA Link': 'm',
  'Paragraph (large)|Heading 2': 'xl',
  'Paragraph (large)|Image': 'l',
  'Paragraph (large)|Paragraph': 'm',
  'Paragraph (large)|Standalone Link': 'm',
  'Paragraph (large)|Table': 'l',
  'Paragraph|\u2026 List': 'm',
  'Paragraph|Button / CTA Link': 'm',
  'Paragraph|Heading 2': 'xl',
  'Paragraph|Heading 3': 'l',
  'Paragraph|Heading 4': 'm',
  'Paragraph|Image': 'l',
  'Paragraph|Paragraph': 'm',
  'Paragraph|Standalone Link': 'm',
  'Paragraph|Table': 'l',
  'Standalone Link|\u2026 List': 'm',
  'Standalone Link|Button / CTA Link': 'm',
  'Standalone Link|Heading 2': 'xl',
  'Standalone Link|Heading 3': 'l',
  'Standalone Link|Heading 4': 'l',
  'Standalone Link|Image': 'l',
  'Standalone Link|Link': 'm',
  'Standalone Link|Paragraph': 'm',
  'Standalone Link|Table': 'l',
  'Table|\u2026 List': 'l',
  'Table|Button / CTA Link': 'l',
  'Table|Heading 2': 'xl',
  'Table|Heading 3': 'xl',
  'Table|Heading 4': 'xl',
  'Table|Image': 'l',
  'Table|Link': 'l',
  'Table|Paragraph': 'l',
  'Table|Table': 'l',
}
