import figma from '@figma/code-connect'
import React from 'react'
import { Alert } from '../src/Alert/Alert'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24373-51087&m=dev',
  {
    example: ({ closable, content, heading, severity }) => (
      <Alert closeable={closable} heading={heading} headingLevel={2} severity={severity}>
        {content}
      </Alert>
    ),
    props: {
      // showheading: figma.boolean('Show heading'),
      closable: figma.boolean('Closable'),
      content: figma.instance('Content'),
      heading: figma.string('Heading'),
      severity: figma.enum('Severity', {
        Error: 'error',
        Success: 'success',
        Warning: 'warning',
      }),
    },
  },
)
