import figma from '@figma/code-connect'
import React from 'react'
import { DemoArticleHeader } from './DemoArticleHeader'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DemoArticleHeader,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24422-8193&m=dev',
  {
    props: {
      children: figma.children(['Heading', 'Paragraph']),
    },
    example: ({ children }) => <DemoArticleHeader>{children}</DemoArticleHeader>,
  },
)
