import figma from '@figma/code-connect'
import React from 'react'
import { Heading } from '../src/Heading/Heading'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Heading,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=16332-106137&m=dev',
  {
    props: {
      text: figma.string('Text'),
      size: figma.enum('Size', {
        '0': 0,
        '1': 1,
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        '6': 6,
      }),
    },
    example: ({ text, size }) => <Heading level={size}>{text}</Heading>,
  },
)
