import figma from '@figma/code-connect'
import React from 'react'
import { OrderedList } from '../src/OrderedList/OrderedList'
import { OrderedListItem } from '../src/OrderedList/OrderedListItem'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  OrderedList,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24205-7721&node-type=frame&m=dev',
  {
    props: {
      children: figma.children(['_Ordered list item']),
      size: figma.enum('Size', {
        Default: undefined,
        Small: 'small',
      }),
    },
    example: ({ children, size }) => <OrderedList size={size}>{children}</OrderedList>,
  },
)

figma.connect(
  OrderedListItem,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24205-8183&node-type=frame&m=dev',
  {
    props: {
      text: figma.string('Text'),
      children: figma.children(['_Ordered list sub list']),
    },
    example: ({ text, children }) => (
      <OrderedList.Item>
        {text}
        {children}
      </OrderedList.Item>
    ),
  },
)

figma.connect(
  OrderedList,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24205-9607&node-type=frame&m=dev',
  {
    props: {
      children: figma.children(['_Ordered list sub item']),
      size: figma.enum('Size', {
        Default: undefined,
        Small: 'small',
      }),
    },
    example: ({ children, size }) => <OrderedList size={size}>{children}</OrderedList>,
  },
)

figma.connect(
  OrderedListItem,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24093-1751&node-type=frame&m=dev',
  {
    props: {
      text: figma.string('Text'),
    },
    example: ({ text }) => <OrderedList.Item>{text}</OrderedList.Item>,
  },
)
