import figma from '@figma/code-connect'
import React from 'react'
import { UnorderedList } from '../src/UnorderedList/UnorderedList'
import { UnorderedListItem } from '../src/UnorderedList/UnorderedListItem'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  UnorderedList,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24090-19658&node-type=frame&m=dev',
  {
    example: ({ children, size }) => <UnorderedList size={size}>{children}</UnorderedList>,
    props: {
      children: figma.children(['_Unordered list item']),
      size: figma.enum('Size', {
        Default: undefined,
        Small: 'small',
      }),
    },
  },
)

figma.connect(
  UnorderedListItem,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24090-20028&node-type=frame&m=dev',
  {
    example: ({ children, text }) => (
      <UnorderedList.Item>
        {text}
        {children}
      </UnorderedList.Item>
    ),
    props: {
      children: figma.children(['_Unordered list sub list']),
      text: figma.string('Text'),
    },
  },
)

figma.connect(
  UnorderedList,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24093-1757&node-type=frame&m=dev',
  {
    example: ({ children, size }) => <UnorderedList size={size}>{children}</UnorderedList>,
    props: {
      children: figma.children(['_Unordered list sub item']),
      size: figma.enum('Size', {
        Default: undefined,
        Small: 'small',
      }),
    },
  },
)

figma.connect(
  UnorderedListItem,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=24093-1751&node-type=frame&m=dev',
  {
    example: ({ text }) => <UnorderedList.Item>{text}</UnorderedList.Item>,
    props: {
      text: figma.string('Text'),
    },
  },
)
