version: 2

# Documentation:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Prod and dev dependencies are split in two groups,
    # because their PRs get a different prefix ('fix' for prod, 'chore' for dev)
    groups:
      patch-and-minor-dependencies:
        applies-to: "version-updates"
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"
      patch-and-minor-dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
