minimumReleaseAge: 1440 # Delay installing a newly published version of a package for 1440 minutes (1 day)
packages:
  - "packages/*"
  - "packages-proprietary/*"
  - "storybook"
overrides:
  "@tootallnate/once@<3.0.1": ">=3.0.1"
  tar: ">=7.5.11"
engineStrict: true
savePrefix: ""
allowBuilds:
  "@bundled-es-modules/glob": false
  "@parcel/watcher": false
  esbuild: false
  sharp: false
  style-dictionary: false
