import figma from '@figma/code-connect'
import { Button } from './Button'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/branch/Sq3xtZaI3e6OtnizqfKR4w/Amsterdam-Design-System?node-id=15700-53370&t=TrURZbZ6TkhD9Nri-11',
  {
    props: {
      // iconshape: figma.instance('Icon shape'),
      text: figma.string('Text'),
      hierarchy: figma.enum('Hierarchy', {
        Primary: 'primary',
        Secondary: 'secondary',
        Tertiary: 'tertiary',
      }),
      // hover: figma.boolean('Hover'),
      // focus: figma.boolean('Focus'),
      disabled: figma.boolean('Disabled'),
      // icon: figma.enum('Icon', {
      //   None: 'none',
      //   Start: 'start',
      //   End: 'end',
      //   Only: 'only',
      // }),
    },
    example: ({ hierarchy, disabled, text }) => (
      <Button variant={hierarchy} disabled={disabled}>
        {text}
      </Button>
    ),
  },
)
