/**
 * @license EUPL-1.2+
 * Copyright Gemeente Amsterdam
 */

export type Team = {
  doelpunten_tegen: number
  doelpunten_voor: number
  doelsaldo: number
  gelijk: number
  gespeeld: number
  gewonnen: number
  positie: number
  punten: number
  team: string
  verloren: number
}

export type Ranking = Team[]

export const ranking: Ranking = [
  {
    doelpunten_tegen: 39,
    doelpunten_voor: 103,
    doelsaldo: 64,
    gelijk: 4,
    gespeeld: 34,
    gewonnen: 25,
    positie: 1,
    punten: 79,
    team: 'PSV',
    verloren: 5,
  },
  {
    doelpunten_tegen: 32,
    doelpunten_voor: 67,
    doelsaldo: 35,
    gelijk: 6,
    gespeeld: 34,
    gewonnen: 24,
    positie: 2,
    punten: 78,
    team: 'Ajax',
    verloren: 4,
  },
  {
    doelpunten_tegen: 38,
    doelpunten_voor: 76,
    doelsaldo: 38,
    gelijk: 8,
    gespeeld: 34,
    gewonnen: 20,
    positie: 3,
    punten: 68,
    team: 'Feyenoord',
    verloren: 6,
  },
  {
    doelpunten_tegen: 45,
    doelpunten_voor: 62,
    doelsaldo: 17,
    gelijk: 10,
    gespeeld: 34,
    gewonnen: 18,
    positie: 4,
    punten: 64,
    team: 'FC Utrecht',
    verloren: 6,
  },
  {
    doelpunten_tegen: 37,
    doelpunten_voor: 58,
    doelsaldo: 21,
    gelijk: 9,
    gespeeld: 34,
    gewonnen: 16,
    positie: 5,
    punten: 57,
    team: 'AZ',
    verloren: 9,
  },
  {
    doelpunten_tegen: 49,
    doelpunten_voor: 62,
    doelsaldo: 13,
    gelijk: 9,
    gespeeld: 34,
    gewonnen: 15,
    positie: 6,
    punten: 54,
    team: 'FC Twente',
    verloren: 10,
  },
  {
    doelpunten_tegen: 55,
    doelpunten_voor: 57,
    doelsaldo: 2,
    gelijk: 9,
    gespeeld: 34,
    gewonnen: 14,
    positie: 7,
    punten: 51,
    team: 'Go Ahead Eagles',
    verloren: 11,
  },
  {
    doelpunten_tegen: 46,
    doelpunten_voor: 51,
    doelsaldo: 5,
    gelijk: 7,
    gespeeld: 34,
    gewonnen: 12,
    positie: 8,
    punten: 43,
    team: 'N.E.C.',
    verloren: 15,
  },
  {
    doelpunten_tegen: 57,
    doelpunten_voor: 42,
    doelsaldo: -15,
    gelijk: 7,
    gespeeld: 34,
    gewonnen: 12,
    positie: 9,
    punten: 43,
    team: 'sc Heerenveen',
    verloren: 15,
  },
  {
    doelpunten_tegen: 51,
    doelpunten_voor: 43,
    doelsaldo: -8,
    gelijk: 11,
    gespeeld: 34,
    gewonnen: 10,
    positie: 10,
    punten: 41,
    team: 'PEC Zwolle',
    verloren: 13,
  },
  {
    doelpunten_tegen: 54,
    doelpunten_voor: 37,
    doelsaldo: -17,
    gelijk: 8,
    gespeeld: 34,
    gewonnen: 11,
    positie: 11,
    punten: 41,
    team: 'Fortuna Sittard',
    verloren: 15,
  },
  {
    doelpunten_tegen: 43,
    doelpunten_voor: 39,
    doelsaldo: -4,
    gelijk: 12,
    gespeeld: 34,
    gewonnen: 9,
    positie: 12,
    punten: 39,
    team: 'Sparta Rotterdam',
    verloren: 13,
  },
  {
    doelpunten_tegen: 53,
    doelpunten_voor: 40,
    doelsaldo: -13,
    gelijk: 9,
    gespeeld: 34,
    gewonnen: 10,
    positie: 13,
    punten: 39,
    team: 'FC Groningen',
    verloren: 15,
  },
  {
    doelpunten_tegen: 63,
    doelpunten_voor: 42,
    doelsaldo: -21,
    gelijk: 11,
    gespeeld: 34,
    gewonnen: 9,
    positie: 14,
    punten: 38,
    team: 'Heracles Almelo',
    verloren: 14,
  },
  {
    doelpunten_tegen: 58,
    doelpunten_voor: 34,
    doelsaldo: -24,
    gelijk: 9,
    gespeeld: 34,
    gewonnen: 8,
    positie: 15,
    punten: 33,
    team: 'NAC Breda',
    verloren: 17,
  },
  {
    doelpunten_tegen: 56,
    doelpunten_voor: 34,
    doelsaldo: -22,
    gelijk: 8,
    gespeeld: 34,
    gewonnen: 6,
    positie: 16,
    punten: 26,
    team: 'Willem II',
    verloren: 20,
  },
  {
    doelpunten_tegen: 74,
    doelpunten_voor: 44,
    doelsaldo: -30,
    gelijk: 7,
    gespeeld: 34,
    gewonnen: 6,
    positie: 17,
    punten: 25,
    team: 'RKC Waalwijk',
    verloren: 21,
  },
  {
    doelpunten_tegen: 64,
    doelpunten_voor: 23,
    doelsaldo: -41,
    gelijk: 10,
    gespeeld: 34,
    gewonnen: 4,
    positie: 18,
    punten: 22,
    team: 'Almere City FC',
    verloren: 20,
  },
]
