import figma from '@figma/code-connect'
import { Badge } from './Badge'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  'https://www.figma.com/design/9IGm6IdPUYizBNGsUnueBd/Amsterdam-Design-System?node-id=17750-42420&m=dev',
  {
    props: {
      label: figma.string('Label'),
      color: figma.enum('Color', {
        Yellow: 'yellow',
        Blue: 'blue',
        Red: 'red',
        Green: 'green',
        Purple: 'purple',
        Magenta: 'magenta',
        Orange: 'orange',
        'Light Blue': 'light-blue',
        White: 'white',
        Black: 'black',
        'Dark Green': 'dark-green',
        'Grey 1': 'grey-1',
        'Grey 2': 'grey-2',
        'Grey 3': 'grey-3',
      }),
    },
    example: ({ label, color }) => <Badge label={label} color={color} />,
  },
)
