export const Hotspots = [
  {
    fromDate: '15-01-2020',
    id: 1,
    name: 'Lepenplein',
    priority: 'Ja',
  },
  {
    fromDate: '15-01-2020',
    id: 2,
    name: 'Metrostation Wiebautstraat',
    priority: 'Ja',
  },
  {
    fromDate: '15-01-2020',
    id: 3,
    name: 'Oosterpark',
    priority: 'Nee',
  },
  {
    fromDate: '15-01-2020',
    id: 4,
    name: 'Timorplein',
    priority: 'Nee',
  },
  {
    fromDate: '05-02-2020',
    id: 5,
    name: 'Oosterspoorplein',
    priority: 'Nee',
  },
  {
    fromDate: '11-05-2020',
    id: 6,
    name: 'jazeker, Nog een hotspot',
    priority: 'Nee',
  },
  {
    fromDate: '13-05-2020',
    id: 7,
    name: 'Arie Biemonds',
    priority: 'Nee',
  },
  {
    fromDate: '13-05-2020',
    id: 8,
    name: 'Waterlooplein',
    priority: 'Nee',
  },
  {
    fromDate: '01-07-2020',
    id: 9,
    name: 'Frederik Hendrikplantsoen',
    priority: 'Nee',
  },
  {
    fromDate: '19-08-2020',
    id: 10,
    name: 'marnixpleintje 15',
    priority: 'Nee',
  },
  {
    fromDate: '29-03-2021',
    id: 11,
    name: 'Veemkade',
    priority: 'Nee',
  },
  {
    fromDate: '12-04-2021',
    id: 12,
    name: 'Marktbureau Albert Cuyp',
    priority: 'Nee',
  },
  {
    fromDate: '30-11-2021',
    id: 13,
    name: 'Flevo',
    priority: 'Nee',
  },
  {
    fromDate: '30-11-2021',
    id: 14,
    name: 'Weesperstraat 113',
    priority: 'Nee',
  },
  {
    fromDate: '20-12-2021',
    id: 15,
    name: 'Sean MacBridestraat',
    priority: 'Nee',
  },
  {
    fromDate: '28-03-2022',
    id: 16,
    name: 'Fenengastraat',
    priority: 'Nee',
  },
  {
    fromDate: '15-09-2022',
    id: 17,
    name: 'Weesperplein',
    priority: 'Nee',
  },
  {
    fromDate: '20-09-2022',
    id: 18,
    name: 'Kromhouthal',
    priority: 'Nee',
  },
]
