export const Meldingen = [
  {
    title: 'Lepenplein',
    addedDate: '15-01-2020',
    id: 1,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Metrostation Wiebautstraat',
    addedDate: '15-01-2020',
    id: 2,
    reporter: false,
    type: 'particulier',
  },
  {
    title: 'Oosterpark',
    addedDate: '15-01-2020',
    id: 3,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Timorplein',
    addedDate: '15-01-2020',
    id: 4,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Oosterspoorplein',
    addedDate: '05-02-2020',
    id: 5,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'jazeker, Nog een hotspot',
    addedDate: '11-05-2020',
    id: 6,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Arie Biemonds',
    addedDate: '13-05-2020',
    id: 7,
    reporter: false,
    type: 'particulier',
  },
  {
    title: 'Waterlooplein',
    addedDate: '13-05-2020',
    id: 8,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Frederik Hendrikplantsoen',
    addedDate: '01-07-2020',
    id: 9,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'marnixpleintje 15',
    addedDate: '19-08-2020',
    id: 10,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Veemkade',
    addedDate: '29-03-2021',
    id: 11,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Marktbureau Albert Cuyp',
    addedDate: '12-04-2021',
    id: 12,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Flevo',
    addedDate: '30-11-2021',
    id: 13,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Weesperstraat 113',
    addedDate: '30-11-2021',
    id: 14,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Sean MacBridestraat',
    addedDate: '20-12-2021',
    id: 15,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Fenengastraat',
    addedDate: '28-03-2022',
    id: 16,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Weesperplein',
    addedDate: '15-09-2022',
    id: 17,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
  {
    title: 'Kromhouthal',
    addedDate: '20-09-2022',
    id: 18,
    reporter: 'Jan Jansen',
    type: 'particulier',
  },
]
