export { Tabs } from './Tabs'
export type { TabsProps } from './Tabs'
export type { TabsPanelProps } from './TabsPanel'
export type { TabsListProps } from './TabsList'
export type { TabsButtonProps } from './TabsButton'
