import { render, screen } from '@testing-library/react'
import { createRef } from 'react'
import { Tabs } from './Tabs'
import '@testing-library/jest-dom'

describe('Tabs Panel', () => {
  it('renders', () => {
    render(
      <Tabs>
        <Tabs.List>
          <Tabs.Button tab="one" />
        </Tabs.List>
        <Tabs.Panel tab="one" />
      </Tabs>,
    )

    const component = screen.getByRole('tabpanel')

    expect(component).toBeInTheDocument()
  })

  it('renders a design system BEM class name', () => {
    render(
      <Tabs>
        <Tabs.List>
          <Tabs.Button tab="one" />
        </Tabs.List>
        <Tabs.Panel tab="one" />
      </Tabs>,
    )

    const component = screen.getByRole('tabpanel')

    expect(component).toHaveClass('ams-tabs__panel')
  })

  it('renders an additional class name', () => {
    render(
      <Tabs>
        <Tabs.List>
          <Tabs.Button tab="one" />
        </Tabs.List>
        <Tabs.Panel className="extra" tab="one" />
      </Tabs>,
    )

    const component = screen.getByRole('tabpanel')

    expect(component).toHaveClass('ams-tabs__panel extra')
  })

  it('renders the correct id based on the tabs prop', () => {
    const { container } = render(
      <Tabs>
        <Tabs.List>
          <Tabs.Button tab="one" />
        </Tabs.List>
        <Tabs.Panel tab="one" />
      </Tabs>,
    )

    // The start of the id is generated by useId, so we only check the end of the id
    const component = container.querySelector('[id$="panel-one"]')

    expect(component).toBeInTheDocument()
  })

  it('should associate the tab with the correct button', () => {
    render(
      <Tabs>
        <Tabs.List>
          <Tabs.Button tab="one" />
        </Tabs.List>
        <Tabs.Panel tab="one" />
      </Tabs>,
    )

    const component = screen.getByRole('tabpanel')

    // The start of the attribute value is generated by useId, so we only check the end of the value
    expect(component).toHaveAttribute('aria-labelledby', expect.stringMatching(/-tab-one$/))
  })

  it('supports ForwardRef in React', () => {
    const ref = createRef<HTMLDivElement>()

    render(
      <Tabs>
        <Tabs.List>
          <Tabs.Button tab="one" />
        </Tabs.List>
        <Tabs.Panel ref={ref} tab="one" />
      </Tabs>,
    )

    const component = screen.getByRole('tabpanel')

    expect(ref.current).toBe(component)
  })
})
