/**
 * @license EUPL-1.2+
 * Copyright Gemeente Amsterdam
 */

export type SpaceSize = '0' | 'xs' | 's' | 'm' | 'l' | 'xl'

export const spaceSizeLabel: Record<SpaceSize, string> = {
  '0': 'none',
  l: 'large',
  m: 'medium',
  s: 'small',
  xl: 'extra large',
  xs: 'extra small',
}

export const componentsAbove = [
  'Heading 1',
  'Heading 2',
  'Heading 3',
  'Heading 4',
  'Blockquote',
  'Description / Link List',
  'Ordered / Unordered List',
  'Paragraph',
  'Paragraph (large)',
  'Button',
  'Call to Action Link',
  'Image',
  'Standalone Link',
  'Table',
]

export const componentsBelow = [
  'Heading 2',
  'Heading 3',
  'Heading 4',
  'Blockquote',
  'Button',
  'Call to Action Link',
  'Image',
  'Standalone Link',
  'Description / Link List',
  'Ordered / Unordered List',
  'Paragraph',
  'Paragraph (large)',
  'Table',
]

export const verticalSpace: Record<string, SpaceSize> = {
  'Blockquote|Button': 'l',
  'Blockquote|Call to Action Link': 'xl',
  'Blockquote|Description / Link List': 'l',
  'Blockquote|Image': 'l',
  'Blockquote|Ordered / Unordered List': 'l',
  'Blockquote|Paragraph': 'l',
  'Blockquote|Standalone Link': 'l',
  'Blockquote|Table': 'l',
  'Button|Blockquote': 'l',
  'Button|Button': 'l',
  'Button|Call to Action Link': 'xl',
  'Button|Description / Link List': 'm',
  'Button|Heading 2': 'xl',
  'Button|Heading 3': 'l',
  'Button|Heading 4': 'l',
  'Button|Image': 'l',
  'Button|Ordered / Unordered List': 'm',
  'Button|Paragraph': 'm',
  'Button|Standalone Link': 'm',
  'Button|Table': 'l',
  'Call to Action Link|Blockquote': 'xl',
  'Call to Action Link|Button': 'xl',
  'Call to Action Link|Description / Link List': 'xl',
  'Call to Action Link|Heading 2': 'xl',
  'Call to Action Link|Heading 3': 'xl',
  'Call to Action Link|Heading 4': 'xl',
  'Call to Action Link|Image': 'xl',
  'Call to Action Link|Ordered / Unordered List': 'xl',
  'Call to Action Link|Paragraph': 'xl',
  'Call to Action Link|Standalone Link': 'xl',
  'Call to Action Link|Table': 'xl',
  'Description / Link List|Blockquote': 'l',
  'Description / Link List|Button': 'm',
  'Description / Link List|Call to Action Link': 'xl',
  'Description / Link List|Description / Link List': 'm',
  'Description / Link List|Heading 2': 'xl',
  'Description / Link List|Heading 3': 'l',
  'Description / Link List|Heading 4': 'm',
  'Description / Link List|Image': 'l',
  'Description / Link List|Ordered / Unordered List': 'm',
  'Description / Link List|Paragraph': 'm',
  'Description / Link List|Standalone Link': 'm',
  'Description / Link List|Table': 'l',
  'Heading 1|Description / Link List': 'm',
  'Heading 1|Heading 2': 'xl',
  'Heading 1|Image': 'm',
  'Heading 1|Ordered / Unordered List': 'm',
  'Heading 1|Paragraph': 'm',
  'Heading 1|Paragraph (large)': 'm',
  'Heading 2|Description / Link List': 's',
  'Heading 2|Heading 3': 'm',
  'Heading 2|Image': 's',
  'Heading 2|Ordered / Unordered List': 's',
  'Heading 2|Paragraph': 's',
  'Heading 2|Standalone Link': 's',
  'Heading 2|Table': 's',
  'Heading 3|Description / Link List': 's',
  'Heading 3|Heading 4': 'm',
  'Heading 3|Image': 's',
  'Heading 3|Ordered / Unordered List': 'xs',
  'Heading 3|Paragraph': 'xs',
  'Heading 3|Standalone Link': 's',
  'Heading 3|Table': 's',
  'Heading 4|Description / Link List': 'xs',
  'Heading 4|Image': 'xs',
  'Heading 4|Ordered / Unordered List': '0',
  'Heading 4|Paragraph': '0',
  'Heading 4|Standalone Link': 'xs',
  'Heading 4|Table': 'xs',
  'Image|Blockquote': 'l',
  'Image|Button': 'l',
  'Image|Call to Action Link': 'xl',
  'Image|Description / Link List': 'l',
  'Image|Heading 2': 'xl',
  'Image|Heading 3': 'l',
  'Image|Heading 4': 'l',
  'Image|Image': 'l',
  'Image|Ordered / Unordered List': 'l',
  'Image|Paragraph': 'l',
  'Image|Standalone Link': 'l',
  'Image|Table': 'l',
  'Ordered / Unordered List|Blockquote': 'l',
  'Ordered / Unordered List|Button': 'm',
  'Ordered / Unordered List|Call to Action Link': 'xl',
  'Ordered / Unordered List|Description / Link List': 'm',
  'Ordered / Unordered List|Heading 2': 'xl',
  'Ordered / Unordered List|Heading 3': 'l',
  'Ordered / Unordered List|Heading 4': 'm',
  'Ordered / Unordered List|Image': 'l',
  'Ordered / Unordered List|Ordered / Unordered List': 'm',
  'Ordered / Unordered List|Paragraph': 'm',
  'Ordered / Unordered List|Standalone Link': 'm',
  'Ordered / Unordered List|Table': 'l',
  'Paragraph (large)|Blockquote': 'xl',
  'Paragraph (large)|Description / Link List': 'l',
  'Paragraph (large)|Heading 2': 'xl',
  'Paragraph (large)|Image': 'xl',
  'Paragraph (large)|Ordered / Unordered List': 'l',
  'Paragraph (large)|Paragraph': 'l',
  'Paragraph (large)|Standalone Link': 'l',
  'Paragraph (large)|Table': 'l',
  'Paragraph|Blockquote': 'l',
  'Paragraph|Button': 'm',
  'Paragraph|Call to Action Link': 'xl',
  'Paragraph|Description / Link List': 'm',
  'Paragraph|Heading 2': 'xl',
  'Paragraph|Heading 3': 'l',
  'Paragraph|Heading 4': 'm',
  'Paragraph|Image': 'l',
  'Paragraph|Ordered / Unordered List': 'm',
  'Paragraph|Paragraph': 'm',
  'Paragraph|Paragraph (large)': 'm',
  'Paragraph|Standalone Link': 's',
  'Paragraph|Table': 'l',
  'Standalone Link|Blockquote': 'l',
  'Standalone Link|Button': 'm',
  'Standalone Link|Call to Action Link': 'xl',
  'Standalone Link|Description / Link List': 'm',
  'Standalone Link|Heading 2': 'xl',
  'Standalone Link|Heading 3': 'l',
  'Standalone Link|Heading 4': 'l',
  'Standalone Link|Image': 'l',
  'Standalone Link|Ordered / Unordered List': 'm',
  'Standalone Link|Paragraph': 'm',
  'Standalone Link|Standalone Link': 'm',
  'Standalone Link|Table': 'l',
  'Table|Blockquote': 'l',
  'Table|Button': 'l',
  'Table|Call to Action Link': 'xl',
  'Table|Description / Link List': 'l',
  'Table|Heading 2': 'xl',
  'Table|Heading 3': 'l',
  'Table|Heading 4': 'l',
  'Table|Image': 'l',
  'Table|Ordered / Unordered List': 'l',
  'Table|Paragraph': 'l',
  'Table|Standalone Link': 'l',
  'Table|Table': 'l',
}
