/**
 * @license EUPL-1.2+
 * Copyright Gemeente Amsterdam
 */

export type SpaceSize = '0' | 'xs' | 's' | 'm' | 'l' | 'xl'

export const spaceSizeLabel: Record<SpaceSize, string> = {
  '0': 'none',
  l: 'large',
  m: 'medium',
  s: 'small',
  xl: 'extra large',
  xs: 'extra small',
}

export const componentsAbove = [
  'Heading 1',
  'Heading 2',
  'Heading 3',
  'Heading 4',
  'Blockquote',
  '\u2026 List',
  'Paragraph',
  'Paragraph (large)',
  'Button',
  'Call to Action Link',
  'Image',
  'Standalone Link',
  'Table',
]

export const componentsBelow = [
  'Heading 2',
  'Heading 3',
  'Heading 4',
  'Blockquote',
  'Button',
  'Call to Action Link',
  'Image',
  'Standalone Link',
  '\u2026 List',
  'Paragraph',
  'Paragraph (large)',
  'Table',
]

export const verticalSpace: Record<string, SpaceSize> = {
  '\u2026 List|\u2026 List': 'm',
  '\u2026 List|Blockquote': 'l',
  '\u2026 List|Button': 'm',
  '\u2026 List|Call to Action Link': 'xl',
  '\u2026 List|Heading 2': 'xl',
  '\u2026 List|Heading 3': 'l',
  '\u2026 List|Heading 4': 'm',
  '\u2026 List|Image': 'l',
  '\u2026 List|Paragraph': 'm',
  '\u2026 List|Standalone Link': 'm',
  '\u2026 List|Table': 'l',
  'Blockquote|\u2026 List': 'l',
  'Blockquote|Button': 'l',
  'Blockquote|Call to Action Link': 'xl',
  'Blockquote|Image': 'l',
  'Blockquote|Paragraph': 'l',
  'Blockquote|Standalone Link': 'l',
  'Blockquote|Table': 'l',
  'Button|\u2026 List': 'm',
  'Button|Blockquote': 'l',
  'Button|Button': 'l',
  'Button|Call to Action Link': 'xl',
  'Button|Heading 2': 'xl',
  'Button|Heading 3': 'l',
  'Button|Heading 4': 'l',
  'Button|Image': 'l',
  'Button|Paragraph': 'm',
  'Button|Standalone Link': 'm',
  'Button|Table': 'l',
  'Call to Action Link|\u2026 List': 'xl',
  'Call to Action Link|Blockquote': 'xl',
  'Call to Action Link|Button': 'xl',
  'Call to Action Link|Heading 2': 'xl',
  'Call to Action Link|Heading 3': 'xl',
  'Call to Action Link|Heading 4': 'xl',
  'Call to Action Link|Image': 'xl',
  'Call to Action Link|Paragraph': 'xl',
  'Call to Action Link|Standalone Link': 'xl',
  'Call to Action Link|Table': 'xl',
  'Heading 1|Heading 2': 'xl',
  'Heading 1|Paragraph': 'm',
  'Heading 1|Paragraph (large)': 'm',
  'Heading 2|\u2026 List': 's',
  'Heading 2|Heading 3': 'm',
  'Heading 2|Paragraph': 's',
  'Heading 2|Table': 's',
  'Heading 3|\u2026 List': 'xs',
  'Heading 3|Heading 4': 'm',
  'Heading 3|Paragraph': 'xs',
  'Heading 3|Table': 'xs',
  'Heading 4|\u2026 List': '0',
  'Heading 4|Paragraph': '0',
  'Heading 4|Table': '0',
  'Image|\u2026 List': 'l',
  'Image|Blockquote': 'l',
  'Image|Button': 'l',
  'Image|Call to Action Link': 'xl',
  'Image|Heading 2': 'xl',
  'Image|Heading 3': 'l',
  'Image|Heading 4': 'l',
  'Image|Image': 'l',
  'Image|Paragraph': 'l',
  'Image|Standalone Link': 'l',
  'Image|Table': 'l',
  'Paragraph (large)|\u2026 List': 'l',
  'Paragraph (large)|Blockquote': 'xl',
  'Paragraph (large)|Heading 2': 'xl',
  'Paragraph (large)|Image': 'xl',
  'Paragraph (large)|Paragraph': 'l',
  'Paragraph (large)|Standalone Link': 'l',
  'Paragraph (large)|Table': 'l',
  'Paragraph|\u2026 List': 'm',
  'Paragraph|Blockquote': 'l',
  'Paragraph|Button': 'm',
  'Paragraph|Call to Action Link': 'xl',
  'Paragraph|Heading 2': 'xl',
  'Paragraph|Heading 3': 'l',
  'Paragraph|Heading 4': 'm',
  'Paragraph|Image': 'l',
  'Paragraph|Paragraph': 'm',
  'Paragraph|Paragraph (large)': 'm',
  'Paragraph|Standalone Link': 's',
  'Paragraph|Table': 'l',
  'Standalone Link|\u2026 List': 'm',
  'Standalone Link|Blockquote': 'l',
  'Standalone Link|Button': 'm',
  'Standalone Link|Call to Action Link': 'xl',
  'Standalone Link|Heading 2': 'xl',
  'Standalone Link|Heading 3': 'l',
  'Standalone Link|Heading 4': 'l',
  'Standalone Link|Image': 'l',
  'Standalone Link|Paragraph': 'm',
  'Standalone Link|Standalone Link': 'm',
  'Standalone Link|Table': 'l',
  'Table|\u2026 List': 'l',
  'Table|Blockquote': 'l',
  'Table|Button': 'l',
  'Table|Call to Action Link': 'xl',
  'Table|Heading 2': 'xl',
  'Table|Heading 3': 'l',
  'Table|Heading 4': 'l',
  'Table|Image': 'l',
  'Table|Paragraph': 'l',
  'Table|Standalone Link': 'l',
  'Table|Table': 'l',
}
