export { default as LogoAmsterdam } from './LogoAmsterdam'
export { default as LogoGgdAmsterdam } from './LogoGgdAmsterdam'
export { default as LogoMuseumWeesp } from './LogoMuseumWeesp'
export { default as LogoStadsarchief } from './LogoStadsarchief'
export { default as LogoStadsbankVanLening } from './LogoStadsbankVanLening'
export { default as LogoVgaVerzekeringen } from './LogoVgaVerzekeringen'
