name: Check bundle size

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

# A new push to the PR makes the run in flight obsolete – cancel it.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  report-bundle-size:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    # This job builds the packages twice: once for the base branch and once for the PR.
    timeout-minutes: 20

    steps:
      - name: Check out branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Set up Node.js version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Create asset aggregates
        run: |
          mkdir -p packages-proprietary/temp
          tar -czf packages-proprietary/temp/assets-fonts.tar.gz -C packages-proprietary/assets font
          tar -czf packages-proprietary/temp/assets-others.tar.gz -C packages-proprietary/assets app-icons favicon icons logo manifest

      - name: Report bundle size
        uses: preactjs/compressed-size-action@f322c295dde06a1cb7ccaef105732dd8a726d1d9 # v2.10.0
        with:
          build-script: build
          install-script: pnpm install --frozen-lockfile --ignore-scripts
          pattern: "{packages/react/dist/index!(*.cjs).js,packages/css/dist/index.css,packages-proprietary/tokens/dist/!(*.theme).css,packages-proprietary/react-icons/dist/index.esm.js,packages-proprietary/temp/assets-fonts.tar.gz,packages-proprietary/temp/assets-others.tar.gz}"
          strip-hash: "\\b\\w{8}\\."

      - name: Clean up asset aggregates
        if: always()
        run: rm -f packages-proprietary/temp/assets-fonts.tar.gz packages-proprietary/temp/assets-others.tar.gz
