name: Check test coverage

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

# A new push to the PR makes the run in flight obsolete – cancel it.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  report-test-coverage:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Set up Node.js version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build icons package
        run: pnpm --filter @amsterdam/design-system-react-icons build

      - name: Run tests with coverage
        run: pnpm --filter @amsterdam/design-system-react test

      - name: Report test coverage
        uses: davelosert/vitest-coverage-report-action@c4bbc33a89b7ace0e63d35f1f7d4bcee31155a73 # v2.13.0
        with:
          json-summary-path: packages/react/coverage/coverage-summary.json
          name: React components
          threshold-icons: '{"0": "🔴", "95": "🟠", "99": "🟢"}'
