name: Bundle size report

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  compressed-size:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0

      - name: Set up Node.js version
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: pnpm
          node-version-file: .nvmrc

      - name: Report bundle size
        uses: preactjs/compressed-size-action@66325aad6443cb7cf89c4bfcd414aea2367cda94 # v2.9.1
        with:
          build-script: build
          install-script: pnpm install --frozen-lockfile
          pattern: "packages/react/dist/**/*.{js,css}"
          strip-hash: "\\b\\w{8}\\."
